name: Build Docs
on:
  push:
    tags:
    - '*'
  workflow_dispatch: {}
jobs:
  build:
    name: build-doc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install https://github.com/z44d/tgram/archive/refs/heads/main.zip
        pip install docstring_parser certifi aiohttp asyncio

    - name: Update the docs
      run: | 
          cd docs
          python generate_schema.py
          python generate_docs.py
          cd ..
          mv docs/docs/* .
          mv docs/tgram_schema.json tgram_schema.json
          rm -rf docs venv __pycache__ tgram .gitignore LICENSE .github pyproject.toml examples
          touch .nojekyll
          git checkout --orphan gh-pages
          git add . -A
          git config user.email "162994967+z44d@users.noreply.github.com"
          git config user.name "GitHub Action <Zaid>"
          git commit -m "Auto update docs"
          git push origin HEAD:gh-pages --force
